# Generated by Django 5.2.17 on 2026-10-09 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0021_remove_gameturn_game_remove_gameturn_genre_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
            migrations.CreateModel(
                name="Player",
                fields=[
                    (
                        "id",
                        models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            primary_key=True,
                            serialize=False,
                        ),
                    ),
                    ("display_name", models.CharField(max_length=50)),
                    (
                        "session_token_hash",
                        models.CharField(
                            blank=True,
                            editable=False,
                            max_length=64,
                            null=True,
                            unique=True,
                        ),
                    ),
                    ("is_connected", models.BooleanField(default=True)),
                    ("joined_at", models.DateTimeField(auto_now_add=True)),
                    ("last_seen_at", models.DateTimeField(auto_now=True)),
                    (
                        "game",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="players",
                            to="games.game",
                        ),
                    ),
                ],
                options={"db_table": "games_player", "ordering": ("joined_at",),},
            ),
            migrations.CreateModel(
                name="Team",
                fields=[
                    (
                        "id",
                        models.BigAutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    ("name", models.CharField(max_length=50)),
                    ("color", models.CharField(max_length=20)),
                    ("position", models.PositiveSmallIntegerField()),
                    (
                        "game",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="teams",
                            to="games.game",
                        ),
                    ),
                    (
                        "leader",
                        models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            related_name="led_teams",
                            to="lobby.player",
                        ),
                    ),
                ],
                options={"db_table": "games_team", "ordering": ("position",),},
            ),
            migrations.AddField(
                model_name="player",
                name="team",
                field=models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="players",
                    to="lobby.team",
                ),
            ),
            migrations.CreateModel(
                name="LeaderVote",
                fields=[
                    (
                        "id",
                        models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            primary_key=True,
                            serialize=False,
                        ),
                    ),
                    ("created_at", models.DateTimeField(auto_now_add=True)),
                    (
                        "candidate",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="leader_votes_received",
                            to="lobby.player",
                        ),
                    ),
                    (
                        "voter",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="leader_votes_cast",
                            to="lobby.player",
                        ),
                    ),
                    (
                        "team",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="leader_votes",
                            to="lobby.team",
                        ),
                    ),
                ],
                options={"db_table": "games_leadervote", "ordering": ("created_at",),},
            ),
            migrations.AddConstraint(
                model_name="team",
                constraint=models.UniqueConstraint(
                    fields=("game", "position"), name="unique_team_position_per_game"
                ),
            ),
            migrations.AddConstraint(
                model_name="team",
                constraint=models.UniqueConstraint(
                    fields=("game", "name"), name="unique_team_name_per_game"
                ),
            ),
            migrations.AddConstraint(
                model_name="player",
                constraint=models.UniqueConstraint(
                    fields=("game", "display_name"), name="unique_player_name_per_game"
                ),
            ),
            migrations.AddConstraint(
                model_name="leadervote",
                constraint=models.UniqueConstraint(
                    fields=("team", "voter"), name="one_leader_vote_per_player"
                ),
            ),
            ],
        ),
    ]

