# Generated by Django 5.2.17 on 2026-10-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="session_token_hash",),
    ]
