# Generated by Django 5.2.17 on 2026-08-12 16:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Music Quiz', max_length=100)),
                ('number_of_teams', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('status', models.CharField(choices=[('LOBBY_OPEN', 'Lobby open'), ('LOBBY_CLOSED', 'Lobby closed'), ('VOTING_OPEN', 'Voting open'), ('READY', 'Ready'), ('IN_PROGRESS', 'In progress'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished')], default='LOBBY_OPEN', max_length=20)),
                ('registration_open', models.BooleanField(default=True)),
                ('current_round', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
