# Generated by Django 5.2.17 on 2026-08-12 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_player_team_player_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='join_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
