# Generated by Django 5.2.17 on 2026-08-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_join_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='session_token_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
