# Generated by Django 5.2.17 on 2026-08-12 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_votes_received', to='games.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_votes', to='games.team')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_votes_cast', to='games.player')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('team', 'voter'), name='one_leader_vote_per_player')],
            },
        ),
    ]
