# Generated by Django 5.2.17 on 2026-08-12 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_leadervote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadervote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
