# Generated by Django 5.2.17 on 2026-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_leadervote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('LOBBY_OPEN', 'Lobby open'), ('LOBBY_CLOSED', 'Lobby closed'), ('VOTING_OPEN', 'Voting open'), ('READY', 'Ready'), ('IN_PROGRESS', 'In progress'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('TEAMS_ASSIGNED', 'Teams assigned'), ('VOTING_CLOSED', 'Voting closed')], default='LOBBY_OPEN', max_length=20),
        ),
    ]
