# Generated by Django 5.2.17 on 2026-08-12 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField()),
                ('turn_position', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('GENRE_SELECTED', 'Genre selected'), ('TRACK_READY', 'Track ready'), ('PLAYING', 'Playing'), ('AWAITING_ANSWER', 'Awaiting answer'), ('ANSWER_REVEALED', 'Answer revealed'), ('COMPLETED', 'Completed')], default='WAITING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='games.game')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turns', to='games.genre')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='games.team')),
            ],
            options={
                'ordering': ('round_number', 'turn_position'),
                'constraints': [models.UniqueConstraint(fields=('game', 'round_number', 'turn_position'), name='unique_turn_position_per_round'), models.UniqueConstraint(fields=('game', 'round_number', 'team'), name='one_turn_per_team_per_round')],
            },
        ),
    ]
