# Generated by Django 5.2.17 on 2026-08-12 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gameturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spotify_track_id', models.CharField(max_length=100, unique=True)),
                ('spotify_uri', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=300)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('artwork_url', models.URLField(blank=True)),
                ('duration_ms', models.PositiveIntegerField()),
                ('is_explicit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('title', 'artist'),
            },
        ),
        migrations.AddField(
            model_name='gameturn',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turns', to='games.track'),
        ),
    ]
