# Generated by Django 5.2.17 on 2026-08-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_track_gameturn_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='spotify_device_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='spotify_device_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
