# Generated by Django 5.2.17 on 2026-08-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_spotify_device_id_game_spotify_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameturn',
            name='playback_start_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='playback_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='playback_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
