# Generated by Django 5.2.17 on 2026-08-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_gameturn_playback_start_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameturn',
            name='answer_revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
