# Generated by Django 5.2.17 on 2026-08-13 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gameturn_answer_revealed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('song_title_correct', models.BooleanField(default=False)),
                ('artist_correct', models.BooleanField(default=False)),
                ('points', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awarded_score_events', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='games.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='games.team')),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_event', to='games.gameturn')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('points__in', (0, 1, 3))), name='score_points_must_be_0_1_or_3')],
            },
        ),
    ]
