# Generated by Django 5.2.17 on 2026-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_scoreevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
