# Generated by Django 5.2.17 on 2026-08-15 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_game_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rounds_per_team',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
