# Generated by Django 5.2.17 on 2026-08-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_game_rounds_per_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='default_playback_start_ms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
