# Generated by Django 5.2.17 on 2026-08-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_game_default_playback_start_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='Track Decode', max_length=100),
        ),
    ]
