# Generated by Django 5.2.17 on 2026-10-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0020_alter_game_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
            migrations.RemoveField(model_name="gameturn", name="game",),
            migrations.RemoveField(model_name="gameturn", name="genre",),
            migrations.RemoveField(model_name="gameturn", name="team",),
            migrations.RemoveField(model_name="gameturn", name="track",),
            migrations.RemoveField(model_name="scoreevent", name="turn",),
            migrations.RemoveField(model_name="leadervote", name="candidate",),
            migrations.RemoveField(model_name="leadervote", name="team",),
            migrations.RemoveField(model_name="leadervote", name="voter",),
            migrations.RemoveField(model_name="player", name="game",),
            migrations.RemoveField(model_name="player", name="team",),
            migrations.RemoveField(model_name="team", name="leader",),
            migrations.RemoveField(model_name="scoreevent", name="awarded_by",),
            migrations.RemoveField(model_name="scoreevent", name="game",),
            migrations.RemoveField(model_name="scoreevent", name="team",),
            migrations.RemoveField(model_name="team", name="game",),
            migrations.DeleteModel(name="Genre",),
            migrations.DeleteModel(name="Track",),
            migrations.DeleteModel(name="GameTurn",),
            migrations.DeleteModel(name="LeaderVote",),
            migrations.DeleteModel(name="Player",),
            migrations.DeleteModel(name="ScoreEvent",),
            migrations.DeleteModel(name="Team",),
            ],
        ),
    ]

