from django.urls import path

from .views import (
    AdvanceTurnView,
    AssignTeamsView,
    AwardScoreView,
    CloseRegistrationView,
    CloseVotingView,
    CsrfTokenView,
    FinishGameView,
    GameListCreateView,
    GameStateView,
    HealthcheckView,
    HostPlayerListView,
    OpenVotingView,
    PlayerJoinView,
    PlayerSessionDetailView,
    PrepareRandomTrackView,
    PublicGameByCodeDetailView,
    PublicGameDetailView,
    PublicLeaderboardView,
    RestartGameView,
    RevealAnswerView,
    SelectRandomGenreView,
    SelectSpotifyDeviceView,
    SpotifyCallbackView,
    SpotifyDeviceListView,
    SpotifyLoginView,
    SpotifyStatusView,
    StartGameView,
    StartNextRoundView,
    StartTrackPlaybackView,
    StopTrackPlaybackView,
    SubmitLeaderVoteView,
    TeamVotingCandidatesView,
    UpdateGameRoundsView,
)

app_name = "games"

urlpatterns = [
    path("csrf/", CsrfTokenView.as_view(), name="csrf-token"),
    path("healthz/", HealthcheckView.as_view(), name="healthcheck"),
    path("games/", GameListCreateView.as_view(), name="game-list-create"),
    path(
        "games/join/code/<str:join_code>/",
        PublicGameByCodeDetailView.as_view(),
        name="public-game-detail-by-code",
    ),
    path(
        "games/join/<uuid:join_token>/",
        PublicGameDetailView.as_view(),
        name="public-game-detail",
    ),
    path(
        "games/join/<uuid:join_token>/players/",
        PlayerJoinView.as_view(),
        name="player-join",
    ),
    path(
        "games/join/<uuid:join_token>/session/",
        PlayerSessionDetailView.as_view(),
        name="player-session-detail",
    ),
    path(
        "games/<uuid:game_id>/players/",
        HostPlayerListView.as_view(),
        name="host-player-list",
    ),
    path(
        "games/<uuid:game_id>/close-registration/",
        CloseRegistrationView.as_view(),
        name="close-registration",
    ),
    path(
        "games/<uuid:game_id>/settings/",
        UpdateGameRoundsView.as_view(),
        name="update-game-rounds",
    ),
    path(
        "games/<uuid:game_id>/assign-teams/",
        AssignTeamsView.as_view(),
        name="assign-teams",
    ),
    path(
        "games/<uuid:game_id>/voting/open/",
        OpenVotingView.as_view(),
        name="open-voting",
    ),
    path(
        "games/join/<uuid:join_token>/voting/",
        SubmitLeaderVoteView.as_view(),
        name="submit-leader-vote",
    ),
    path(
        "games/join/<uuid:join_token>/voting/candidates/",
        TeamVotingCandidatesView.as_view(),
        name="team-voting-candidates",
    ),
    path(
        "games/<uuid:game_id>/voting/close/",
        CloseVotingView.as_view(),
        name="close-voting",
    ),
    path(
        "games/<uuid:game_id>/start/",
        StartGameView.as_view(),
        name="start-game",
    ),
    path(
        ("games/join/<uuid:join_token>/turns/<uuid:turn_id>/genre/"),
        SelectRandomGenreView.as_view(),
        name="select-random-genre",
    ),
    path(
        "spotify/login/",
        SpotifyLoginView.as_view(),
        name="spotify-login",
    ),
    path(
        "spotify/callback/",
        SpotifyCallbackView.as_view(),
        name="spotify-callback",
    ),
    path(
        "spotify/status/",
        SpotifyStatusView.as_view(),
        name="spotify-status",
    ),
    path(
        "games/<uuid:game_id>/turns/<uuid:turn_id>/track/prepare/",
        PrepareRandomTrackView.as_view(),
        name="prepare-random-track",
    ),
    path(
        "spotify/devices/",
        SpotifyDeviceListView.as_view(),
        name="spotify-device-list",
    ),
    path(
        "games/<uuid:game_id>/spotify/device/",
        SelectSpotifyDeviceView.as_view(),
        name="select-spotify-device",
    ),
    path(
        "games/<uuid:game_id>/turns/<uuid:turn_id>/playback/start/",
        StartTrackPlaybackView.as_view(),
        name="start-track-playback",
    ),
    path(
        "games/<uuid:game_id>/turns/<uuid:turn_id>/playback/stop/",
        StopTrackPlaybackView.as_view(),
        name="stop-track-playback",
    ),
    path(
        "games/<uuid:game_id>/turns/<uuid:turn_id>/answer/reveal/",
        RevealAnswerView.as_view(),
        name="reveal-answer",
    ),
    path(
        "games/<uuid:game_id>/turns/<uuid:turn_id>/score/",
        AwardScoreView.as_view(),
        name="award-score",
    ),
    path(
        "games/<uuid:game_id>/turns/<uuid:turn_id>/advance/",
        AdvanceTurnView.as_view(),
        name="advance-turn",
    ),
    path(
        "games/join/<uuid:join_token>/leaderboard/",
        PublicLeaderboardView.as_view(),
        name="public-leaderboard",
    ),
    path(
        "games/<uuid:game_id>/rounds/next/",
        StartNextRoundView.as_view(),
        name="start-next-round",
    ),
    path(
        "games/<uuid:game_id>/finish/",
        FinishGameView.as_view(),
        name="finish-game",
    ),
    path(
        "games/<uuid:game_id>/restart/",
        RestartGameView.as_view(),
        name="restart-game",
    ),
    path(
        "games/<uuid:join_token>/state/",
        GameStateView.as_view(),
        name="game-state",
    ),
]
