# Generated by Django 5.2.17 on 2026-10-09 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0021_remove_gameturn_game_remove_gameturn_genre_and_more"),
        ("lobby", "0001_initial"),
        ("music", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
            migrations.CreateModel(
                name="GameTurn",
                fields=[
                    (
                        "id",
                        models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            primary_key=True,
                            serialize=False,
                        ),
                    ),
                    ("playback_start_ms", models.PositiveIntegerField(default=0)),
                    ("playback_started_at", models.DateTimeField(blank=True, null=True)),
                    ("playback_stopped_at", models.DateTimeField(blank=True, null=True)),
                    ("round_number", models.PositiveIntegerField()),
                    ("turn_position", models.PositiveSmallIntegerField()),
                    (
                        "status",
                        models.CharField(
                            choices=[
                                ("WAITING", "Waiting"),
                                ("ACTIVE", "Active"),
                                ("GENRE_SELECTED", "Genre selected"),
                                ("TRACK_READY", "Track ready"),
                                ("PLAYING", "Playing"),
                                ("AWAITING_ANSWER", "Awaiting answer"),
                                ("ANSWER_REVEALED", "Answer revealed"),
                                ("COMPLETED", "Completed"),
                            ],
                            default="WAITING",
                            max_length=20,
                        ),
                    ),
                    ("answer_revealed_at", models.DateTimeField(blank=True, null=True)),
                    ("started_at", models.DateTimeField(blank=True, null=True)),
                    ("completed_at", models.DateTimeField(blank=True, null=True)),
                    ("created_at", models.DateTimeField(auto_now_add=True)),
                    (
                        "game",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="turns",
                            to="games.game",
                        ),
                    ),
                    (
                        "genre",
                        models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.PROTECT,
                            related_name="turns",
                            to="music.genre",
                        ),
                    ),
                    (
                        "team",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="turns",
                            to="lobby.team",
                        ),
                    ),
                    (
                        "track",
                        models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.PROTECT,
                            related_name="turns",
                            to="music.track",
                        ),
                    ),
                ],
                options={
                    "db_table": "games_gameturn",
                    "ordering": ("round_number", "turn_position"),
                },
            ),
            migrations.CreateModel(
                name="ScoreEvent",
                fields=[
                    (
                        "id",
                        models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            primary_key=True,
                            serialize=False,
                        ),
                    ),
                    ("song_title_correct", models.BooleanField(default=False)),
                    ("artist_correct", models.BooleanField(default=False)),
                    ("points", models.PositiveSmallIntegerField()),
                    ("created_at", models.DateTimeField(auto_now_add=True)),
                    (
                        "awarded_by",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.PROTECT,
                            related_name="awarded_score_events",
                            to=settings.AUTH_USER_MODEL,
                        ),
                    ),
                    (
                        "game",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="score_events",
                            to="games.game",
                        ),
                    ),
                    (
                        "team",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="score_events",
                            to="lobby.team",
                        ),
                    ),
                    (
                        "turn",
                        models.OneToOneField(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="score_event",
                            to="gameplay.gameturn",
                        ),
                    ),
                ],
                options={"db_table": "games_scoreevent", "ordering": ("created_at",),},
            ),
            migrations.AddConstraint(
                model_name="gameturn",
                constraint=models.UniqueConstraint(
                    fields=("game", "round_number", "turn_position"),
                    name="unique_turn_position_per_round",
                ),
            ),
            migrations.AddConstraint(
                model_name="gameturn",
                constraint=models.UniqueConstraint(
                    fields=("game", "round_number", "team"),
                    name="one_turn_per_team_per_round",
                ),
            ),
            migrations.AddConstraint(
                model_name="scoreevent",
                constraint=models.CheckConstraint(
                    condition=models.Q(("points__in", (0, 1, 3))),
                    name="score_points_must_be_0_1_or_3",
                ),
            ),
            ],
        ),
    ]

