# Generated by Django 5.2.17 on 2026-10-09 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0021_remove_gameturn_game_remove_gameturn_genre_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
            migrations.CreateModel(
                name="Genre",
                fields=[
                    (
                        "id",
                        models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            primary_key=True,
                            serialize=False,
                        ),
                    ),
                    ("name", models.CharField(max_length=50, unique=True)),
                    ("color", models.CharField(default="#6366F1", max_length=20)),
                    ("spotify_playlist_id", models.CharField(blank=True, max_length=100)),
                    ("is_enabled", models.BooleanField(default=True)),
                    ("exclude_explicit", models.BooleanField(default=True)),
                    ("created_at", models.DateTimeField(auto_now_add=True)),
                ],
                options={"db_table": "games_genre", "ordering": ("name",),},
            ),
            migrations.CreateModel(
                name="Track",
                fields=[
                    (
                        "id",
                        models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            primary_key=True,
                            serialize=False,
                        ),
                    ),
                    ("spotify_track_id", models.CharField(max_length=100, unique=True)),
                    ("spotify_uri", models.CharField(max_length=150, unique=True)),
                    ("title", models.CharField(max_length=200)),
                    ("artist", models.CharField(max_length=300)),
                    ("album", models.CharField(blank=True, max_length=200)),
                    ("artwork_url", models.URLField(blank=True)),
                    ("duration_ms", models.PositiveIntegerField()),
                    ("is_explicit", models.BooleanField(default=False)),
                    ("created_at", models.DateTimeField(auto_now_add=True)),
                ],
                options={"db_table": "games_track", "ordering": ("title", "artist"),},
            ),
            ],
        ),
    ]

